"""SQLAlchemy ORM models for the Law Agent database.

This module defines declarative models for:
- Document: Legal documents with full-text search support
- Relation: Document relationships forming a DAG (Directed Acyclic Graph)

The models are mapped to the PostgreSQL database schema created during Phase 1 migration.

Document Hierarchy:
- Laws: Primary legislation (level 1)
- Regulations: Implementation rules and amendments (level 2)
- Advisory Opinions: Legal interpretations (level 3)
- Court Rulings: Case law applying laws (level 4)
- Unified Precedents: Supreme Court opinions (level 4)

Relationships (Document.relations_to, Document.relations_from):
- قوانین (laws): Parent law citations
- مواد مرتبط (related articles): Related documents at same level
"""

from typing import Any

from sqlalchemy import (
    ARRAY,
    BIGINT,
    TEXT,
    VARCHAR,
    Column,
    Date,
    ForeignKey,
    Index,
    Integer,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import DeclarativeBase, Mapped, relationship

__all__ = ["Base", "Document", "Relation"]


class Base(DeclarativeBase):
    """SQLAlchemy declarative base for all ORM models."""

    pass


class Document(Base):
    """Legal document stored in the knowledge base.

    Attributes:
        doc_id: Unique document identifier (BIGINT)
        title: Document title in Persian
        doc_type: Type of document (law, regulation, advisory_opinion, court_ruling, unified_precedent)
        date: Document date (Gregorian calendar)
        summary: 200-500 word summary for search and preview
        full_content: Complete document text for answering questions
        tags: Array of subject classifications (stored as PostgreSQL text[])
        search_vector: PostgreSQL tsvector for full-text search (auto-generated by triggers)

    Relationships:
        relations_to: Documents referenced by this document (outgoing edges)
        relations_from: Documents that reference this document (incoming edges)
    """

    __tablename__ = "documents"

    # Primary key
    doc_id = Column(BIGINT, primary_key=True, autoincrement=False)

    # Core metadata
    title = Column(VARCHAR, nullable=False, index=True)
    doc_type = Column(
        VARCHAR, nullable=False
    )  # law, regulation, advisory_opinion, court_ruling, unified_precedent
    date = Column(Date, nullable=True)

    # Content (lazy loaded for large documents)
    summary = Column(TEXT, nullable=True)
    full_content = Column(TEXT, nullable=True)

    # Classification and search
    tags: Any = Column(ARRAY(VARCHAR), nullable=True)  # PostgreSQL text array
    search_vector = Column(TSVECTOR, nullable=True)  # Auto-generated by PostgreSQL triggers

    # Relationships (defined in Relation model below)
    relations_to: Mapped[list["Relation"]] = relationship(
        "Relation",
        foreign_keys="Relation.src_doc_id",
        backref="source_document",
        lazy="select",
        cascade="all, delete-orphan",
    )

    relations_from: Mapped[list["Relation"]] = relationship(
        "Relation",
        foreign_keys="Relation.dst_doc_id",
        backref="destination_document",
        lazy="select",
        cascade="all, delete-orphan",
    )

    # Indexes for common queries
    __table_args__ = (
        Index("ix_documents_title", "title"),
        Index("ix_documents_doc_type", "doc_type"),
        Index("ix_documents_date", "date"),
        # Full-text search index (should already exist from migration)
        # Index("ix_documents_search_vector", "search_vector", postgresql_using="gin"),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<Document(doc_id={self.doc_id}, title={self.title[:50]}, type={self.doc_type})>"

    def get_related_documents(self, relation_type: str | None = None) -> list["Document"]:
        """Get documents related to this one.

        Args:
            relation_type: Filter by specific relation type (e.g., 'قوانین', 'مواد مرتبط')

        Returns:
            List of related Document objects
        """
        related = []

        for relation in self.relations_to:
            if relation_type is None or relation.relation_type == relation_type:
                related.append(relation.destination_document)  # type: ignore[attr-defined]

        return related

    def get_cited_documents(self) -> list["Document"]:
        """Get documents that cite this one (useful for finding laws by their rulings).

        Returns:
            List of Document objects that have relations to this document
        """
        cited_by = []

        for relation in self.relations_from:
            cited_by.append(relation.source_document)  # type: ignore[attr-defined]

        return cited_by


class Relation(Base):
    """Document relationship representing citations and references.

    Forms a Directed Acyclic Graph (DAG) of legal documents where:
    - src_doc_id → dst_doc_id means "src_doc references dst_doc"

    Relation types (stored in Persian):
    - قوانین: Parent law citations (hierarchical, usually up the chain)
    - مواد مرتبط: Related articles (lateral connections)

    Attributes:
        id: Unique relation identifier
        src_doc_id: Source document ID (document making the reference)
        dst_doc_id: Destination document ID (document being referenced)
        relation_type: Type of relationship in Persian
    """

    __tablename__ = "relations"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign keys
    src_doc_id = Column(BIGINT, ForeignKey("documents.doc_id"), nullable=False, index=True)
    dst_doc_id = Column(BIGINT, ForeignKey("documents.doc_id"), nullable=False, index=True)

    # Relationship metadata
    relation_type = Column(VARCHAR, nullable=True)  # قوانین, مواد مرتبط, etc.

    # Indexes for graph traversal
    __table_args__ = (
        Index("ix_relations_src_doc_id", "src_doc_id"),
        Index("ix_relations_dst_doc_id", "dst_doc_id"),
        Index("ix_relations_type", "relation_type"),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return (
            f"<Relation(src={self.src_doc_id}, dst={self.dst_doc_id}, type={self.relation_type})>"
        )
